# Generated by Django 5.2.5 on 2025-09-02 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("labels", models.JSONField(default=dict)),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContentAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("track_id", models.UUIDField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                ("plays", models.BigIntegerField(default=0)),
                ("completes", models.BigIntegerField(default=0)),
                ("skips", models.BigIntegerField(default=0)),
                ("avg_listen_ms", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("track_id", "date")},
            },
        ),
        migrations.CreateModel(
            name="PlayHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("track_id", models.UUIDField(db_index=True)),
                ("started_at", models.DateTimeField(db_index=True)),
                ("ended_at", models.DateTimeField(null=True)),
                ("position_ms", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(null=True)),
                ("device_info", models.JSONField(default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="play_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("play_seconds", models.BigIntegerField(default=0)),
                ("plays", models.IntegerField(default=0)),
                ("unique_tracks", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
