# Generated by Django 5.2.5 on 2025-09-01 20:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="playlist_search_vector_idx"
            ),
        ),
    ]
