# Generated by Django 5.2.5 on 2025-09-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0002_playlist_search_vector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playlist",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playlist",
            name="reposts_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
