# Generated by Django 5.2.5 on 2025-09-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0003_playlist_comments_count_playlist_likes_count_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LikedSongs",
        ),
    ]
