# Generated by Django 5.2.5 on 2025-08-30 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
