# Generated by Django 5.2.5 on 2025-09-01 20:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0003_enable_postgres_extensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="album_search_vector_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="artist_search_vector_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="track_search_vector_idx"
            ),
        ),
    ]
