# Generated by Django 5.2.5 on 2025-09-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0004_album_search_vector_artist_search_vector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="album",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="track",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="track",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="track",
            name="reposts_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
