# Generated by Django 5.2.5 on 2025-09-01 16:24

from django.db import migrations


def migrate_artist_followers_to_user_following(apps, schema_editor):
    '''
    Migrates data from the old artists.ArtistFollower model to the new social.UserFollowing model.
    '''
    try:
        ArtistFollower = apps.get_model('artists', 'ArtistFollower')
        UserFollowing = apps.get_model('social', 'UserFollowing')
    except LookupError:
        # This can happen if the app or model was removed in a future migration.
        # In that case, we can safely assume the migration is not needed.
        return

    new_followings = []
    # Use .iterator() to avoid loading all objects into memory at once
    for old_follow in ArtistFollower.objects.all().iterator():
        new_followings.append(
            UserFollowing(
                id=old_follow.id,
                follower_id=old_follow.user_id,
                followee_artist_id=old_follow.artist_id,
                created_at=old_follow.created_at,
                updated_at=old_follow.updated_at,
            )
        )

    if new_followings:
        UserFollowing.objects.bulk_create(new_followings, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('artists', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_artist_followers_to_user_following, migrations.RunPython.noop),
    ]
