# Generated by Django 5.2.5 on 2025-09-01 16:25

from django.db import migrations


def migrate_liked_songs_to_social_interaction(apps, schema_editor):
    '''
    Migrates data from the old playlists.LikedSongs model to the new social.SocialInteraction model.
    '''
    try:
        LikedSongs = apps.get_model('playlists', 'LikedSongs')
        SocialInteraction = apps.get_model('social', 'SocialInteraction')
    except LookupError:
        return

    new_interactions = []
    for liked_song in LikedSongs.objects.all().iterator():
        new_interactions.append(
            SocialInteraction(
                id=liked_song.id,
                user_id=liked_song.user_id,
                interaction_type='like',
                object_type='track',
                object_id=liked_song.track_id,
                created_at=liked_song.created_at,
                updated_at=liked_song.updated_at,
            )
        )

    if new_interactions:
        SocialInteraction.objects.bulk_create(new_interactions, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_migrate_artist_followers'),
        ('playlists', '0001_initial'), # where LikedSongs is defined
        ('artists', '0001_initial'), # for Track model
    ]

    operations = [
        migrations.RunPython(migrate_liked_songs_to_social_interaction, migrations.RunPython.noop),
    ]
