# Generated by Django 5.2.5 on 2025-09-01 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField(db_index=True)),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Aggregated number of times this query was searched.",
                    ),
                ),
                (
                    "avg_click_rate",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Search Analytics",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="TrendingContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("track", "Track"),
                            ("album", "Album"),
                            ("artist", "Artist"),
                            ("playlist", "Playlist"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content_id", models.UUIDField()),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Final trending score.",
                        max_digits=10,
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Trending Contents",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("track", "Track"),
                            ("album", "Album"),
                            ("artist", "Artist"),
                            ("playlist", "Playlist"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "item_id",
                    models.UUIDField(
                        help_text="Points to the ID of the Track/Album/Artist/Playlist."
                    ),
                ),
                ("score", models.DecimalField(decimal_places=6, max_digits=8)),
                (
                    "model_version",
                    models.CharField(
                        help_text="Which recommendation model version produced this.",
                        max_length=32,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Why this item was recommended.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user for whom the recommendation is. Null for global recommendations.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField()),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        help_text="e.g. {'type': 'track', 'genre': 'rock'}",
                        null=True,
                    ),
                ),
                ("results_count", models.IntegerField()),
                (
                    "clicked_item",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata of the first clicked item.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the search. Null for anonymous users.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
