# Generated by Django 5.2.5 on 2025-08-30 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0002_artist_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_file",
                    models.FileField(upload_to="tracks/original_masters/"),
                ),
                (
                    "hls_master",
                    models.FileField(
                        blank=True,
                        help_text="HLS playlist (.m3u8)",
                        null=True,
                        upload_to="tracks/hls/",
                    ),
                ),
                (
                    "dash_master",
                    models.FileField(
                        blank=True,
                        help_text="DASH manifest (.mpd)",
                        null=True,
                        upload_to="tracks/dash/",
                    ),
                ),
                ("waveform_json", models.JSONField(blank=True, null=True)),
                (
                    "bitrate_kbps",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("sample_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("channels", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "loudness_lufs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="duration, codec, format, key, bpm"
                    ),
                ),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_file_data",
                        to="artists.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio File",
                "verbose_name_plural": "Audio Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AudioQuality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bitrate_kbps", models.PositiveSmallIntegerField()),
                (
                    "resolution_label",
                    models.CharField(help_text="e.g., 64kbps, 128kbps", max_length=20),
                ),
                ("file", models.FileField(upload_to="tracks/transcoded/")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("hls", "HLS"),
                            ("dash", "DASH"),
                            ("mp3", "MP3"),
                            ("aac", "AAC"),
                            ("flac", "FLAC"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualities",
                        to="streaming.audiofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio Quality",
                "verbose_name_plural": "Audio Qualities",
                "ordering": ["audio_file", "-bitrate_kbps"],
            },
        ),
        migrations.CreateModel(
            name="PlaybackSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("autoplay_next", models.BooleanField(default=True)),
                ("crossfade_seconds", models.PositiveSmallIntegerField(default=0)),
                ("shuffle", models.BooleanField(default=False)),
                (
                    "default_quality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="streaming.audioquality",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playback Settings",
                "verbose_name_plural": "Playback Settings",
            },
        ),
        migrations.CreateModel(
            name="StreamingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_position_ms", models.PositiveIntegerField(default=0)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device_info",
                    models.JSONField(
                        blank=True, help_text="user_agent, IP, device", null=True
                    ),
                ),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streaming_sessions",
                        to="streaming.audiofile",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streaming_sessions",
                        to="artists.track",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streaming_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Streaming Session",
                "verbose_name_plural": "Streaming Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="audioquality",
            index=models.Index(
                fields=["audio_file", "bitrate_kbps"],
                name="streaming_a_audio_f_659f6d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="audioquality",
            constraint=models.UniqueConstraint(
                fields=("audio_file", "bitrate_kbps", "format"),
                name="unique_quality_for_file",
            ),
        ),
        migrations.AddIndex(
            model_name="streamingsession",
            index=models.Index(
                fields=["user", "track", "started_at"],
                name="streaming_s_user_id_0e677e_idx",
            ),
        ),
    ]
